export const countriesList =
    [{ key: "AD", flag: "ad", value: "Andorra", text: "Andorra" },
    { key: "AE", flag: "ae", value: "United Arab Emirates", text: "United Arab Emirates" },
    { key: "AF", flag: "af", value: "Afghanistan", text: "Afghanistan" },
    { key: "AG", flag: "ag", value: "Antigua and Barbuda", text: "Antigua and Barbuda" },
    { key: "AI", flag: "ai", value: "Anguilla", text: "Anguilla" },
    { key: "AL", flag: "al", value: "Albania", text: "Albania" },
    { key: "AM", flag: "am", value: "Armenia", text: "Armenia" },
    { key: "AN", flag: "an", value: "Netherlands Antilles", text: "Netherlands Antilles" },
    { key: "AO", flag: "ao", value: "Angola", text: "Angola" },
    { key: "AR", flag: "ar", value: "Argentina", text: "Argentina" },
    { key: "AS", flag: "as", value: "American Samoa", text: "American Samoa" },
    { key: "AT", flag: "at", value: "Austria", text: "Austria" },
    { key: "AU", flag: "au", value: "Australia", text: "Australia" },
    { key: "AW", flag: "aw", value: "Aruba", text: "Aruba" },
    { key: "AZ", flag: "az", value: "Azerbaijan", text: "Azerbaijan" },
    { key: "BA", flag: "ba", value: "Bosnia and Herzegovina", text: "Bosnia and Herzegovina" },
    { key: "BB", flag: "bb", value: "Barbados", text: "Barbados" },
    { key: "BD", flag: "bd", value: "Bangladesh", text: "Bangladesh" },
    { key: "BE", flag: "be", value: "Belgium", text: "Belgium" },
    { key: "BF", flag: "bf", value: "Burkina Faso", text: "Burkina Faso" },
    { key: "BG", flag: "bg", value: "Bulgaria", text: "Bulgaria" },
    { key: "BH", flag: "bh", value: "Bahrain", text: "Bahrain" },
    { key: "BI", flag: "bi", value: "Burundi", text: "Burundi" },
    { key: "BJ", flag: "bj", value: "Benin", text: "Benin" },
    { key: "BM", flag: "bm", value: "Bermuda", text: "Bermuda" },
    { key: "BN", flag: "bn", value: "Brunei Darussalam", text: "Brunei Darussalam" },
    { key: "BO", flag: "bo", value: "Bolivia Plurinational State of", text: "Bolivia Plurinational State of" },
    { key: "BR", flag: "br", value: "Brazil", text: "Brazil" },
    { key: "BS", flag: "bs", value: "Bahamas", text: "Bahamas" },
    { key: "BT", flag: "bt", value: "Bhutan", text: "Bhutan" },
    { key: "BV", flag: "bv", value: "Bouvet Island", text: "Bouvet Island" },
    { key: "BW", flag: "bw", value: "Botswana", text: "Botswana" },
    { key: "BY", flag: "by", value: "Belarus", text: "Belarus" },
    { key: "BZ", flag: "bz", value: "Belize", text: "Belize" },
    { key: "CA", flag: "ca", value: "Canada", text: "Canada" },
    { key: "CC", flag: "cc", value: "Cocos (Keeling) Islands", text: "Cocos (Keeling) Islands" },
    { key: "CD", flag: "cd", value: "Congo the Democratic Republic of the", text: "Congo the Democratic Republic of the" },
    { key: "CF", flag: "cf", value: "Central African Republic", text: "Central African Republic" },
    { key: "CG", flag: "cg", value: "Congo", text: "Congo" },
    { key: "CH", flag: "ch", value: "Switzerland", text: "Switzerland" },
    { key: "CK", flag: "ck", value: "Cook Islands", text: "Cook Islands" },
    { key: "CL", flag: "cl", value: "Chile", text: "Chile" },
    { key: "CM", flag: "cm", value: "Cameroon", text: "Cameroon" },
    { key: "CN", flag: "cn", value: "China", text: "China" },
    { key: "CO", flag: "co", value: "Colombia", text: "Colombia" },
    { key: "CR", flag: "cr", value: "Costa Rica", text: "Costa Rica" },
    { key: "CU", flag: "cu", value: "Cuba", text: "Cuba" },
    { key: "CV", flag: "cv", value: "Cape Verde", text: "Cape Verde" },
    { key: "CX", flag: "cx", value: "Christmas Island", text: "Christmas Island" },
    { key: "CY", flag: "cy", value: "Cyprus", text: "Cyprus" },
    { key: "CZ", flag: "cz", value: "Czech Republic", text: "Czech Republic" },
    { key: "DE", flag: "de", value: "Germany", text: "Germany" },
    { key: "DJ", flag: "dj", value: "Djibouti", text: "Djibouti" },
    { key: "DK", flag: "dk", value: "Denmark", text: "Denmark" },
    { key: "DM", flag: "dm", value: "Dominica", text: "Dominica" },
    { key: "DO", flag: "do", value: "Dominican Republic", text: "Dominican Republic" },
    { key: "DZ", flag: "dz", value: "Algeria", text: "Algeria" },
    { key: "EC", flag: "ec", value: "Ecuador", text: "Ecuador" },
    { key: "EE", flag: "ee", value: "Estonia", text: "Estonia" },
    { key: "EG", flag: "eg", value: "Egypt", text: "Egypt" },
    { key: "EH", flag: "eh", value: "Western Sahara", text: "Western Sahara" },
    { key: "ER", flag: "er", value: "Eritrea", text: "Eritrea" },
    { key: "ES", flag: "es", value: "Spain", text: "Spain" },
    { key: "ET", flag: "et", value: "Ethiopia", text: "Ethiopia" },
    { key: "EU", flag: "eu", value: "Europe", text: "Europe" },
    { key: "FI", flag: "fi", value: "Finland", text: "Finland" },
    { key: "FJ", flag: "fj", value: "Fiji", text: "Fiji" },
    { key: "FK", flag: "fk", value: "Falkland Islands (Malvinas)", text: "Falkland Islands (Malvinas)" },
    { key: "FM", flag: "fm", value: "Micronesia Federated States of", text: "Micronesia Federated States of" },
    { key: "FO", flag: "fo", value: "Faroe Islands", text: "Faroe Islands" },
    { key: "FR", flag: "fr", value: "France", text: "France" },
    { key: "GA", flag: "ga", value: "Gabon", text: "Gabon" },
    { key: "ENG", flag: "gb", value: "England", text: "England" },
    { key: "GB", flag: "gb", value: "United Kingdom", text: "United Kingdom" },
    { key: "GD", flag: "gd", value: "Grenada", text: "Grenada" },
    { key: "GE", flag: "ge", value: "Georgia", text: "Georgia" },
    { key: "GF", flag: "gf", value: "French Guiana", text: "French Guiana" },
    { key: "GH", flag: "gh", value: "Ghana", text: "Ghana" },
    { key: "GI", flag: "gi", value: "Gibraltar", text: "Gibraltar" },
    { key: "GL", flag: "gl", value: "Greenland", text: "Greenland" },
    { key: "GM", flag: "gm", value: "Gambia", text: "Gambia" },
    { key: "GN", flag: "gn", value: "Guinea", text: "Guinea" },
    { key: "GP", flag: "gp", value: "Guadeloupe", text: "Guadeloupe" },
    { key: "GQ", flag: "gq", value: "Equatorial Guinea", text: "Equatorial Guinea" },
    { key: "GR", flag: "gr", value: "Greece", text: "Greece" },
    { key: "GS", flag: "gs", value: "South Georgia and the South Sandwich Islands", text: "South Georgia and the South Sandwich Islands" },
    { key: "GT", flag: "gt", value: "Guatemala", text: "Guatemala" },
    { key: "GU", flag: "gu", value: "Guam", text: "Guam" },
    { key: "GW", flag: "gw", value: "Guinea-Bissau", text: "Guinea-Bissau" },
    { key: "GY", flag: "gy", value: "Guyana", text: "Guyana" },
    { key: "HK", flag: "hk", value: "Hong Kong", text: "Hong Kong" },
    { key: "HM", flag: "hm", value: "Heard Island and McDonald Islands", text: "Heard Island and McDonald Islands" },
    { key: "HN", flag: "hn", value: "Honduras", text: "Honduras" },
    { key: "HR", flag: "hr", value: "Croatia", text: "Croatia" },
    { key: "HT", flag: "ht", value: "Haiti", text: "Haiti" },
    { key: "HU", flag: "hu", value: "Hungary", text: "Hungary" },
    { key: "ID", flag: "id", value: "Indonesia", text: "Indonesia" },
    { key: "IE", flag: "ie", value: "Ireland", text: "Ireland" },
    { key: "IL", flag: "il", value: "Israel", text: "Israel" },
    { key: "IN", flag: "in", value: "India", text: "India" },
    { key: "IO", flag: "io", value: "British Indian Ocean Territory", text: "British Indian Ocean Territory" },
    { key: "IQ", flag: "iq", value: "Iraq", text: "Iraq" },
    { key: "IR", flag: "ir", value: "Iran, Islamic Republic of", text: "Iran, Islamic Republic of" },
    { key: "IS", flag: "is", value: "Iceland", text: "Iceland" },
    { key: "IT", flag: "it", value: "Italy", text: "Italy" },
    { key: "JM", flag: "jm", value: "Jamaica", text: "Jamaica" },
    { key: "JO", flag: "jo", value: "Jordan", text: "Jordan" },
    { key: "JP", flag: "jp", value: "Japan", text: "Japan" },
    { key: "KE", flag: "ke", value: "Kenya", text: "Kenya" },
    { key: "KG", flag: "kg", value: "Kyrgyzstan", text: "Kyrgyzstan" },
    { key: "KH", flag: "kh", value: "Cambodia", text: "Cambodia" },
    { key: "KI", flag: "ki", value: "Kiribati", text: "Kiribati" },
    { key: "KM", flag: "km", value: "Comoros", text: "Comoros" },
    { key: "KN", flag: "kn", value: "Saint Kitts and Nevis", text: "Saint Kitts and Nevis" },
    { key: "KP", flag: "kp", value: "Korea Democratic People's Republic of", text: "Korea Democratic People's Republic of" },
    { key: "KR", flag: "kr", value: "Korea Republic of", text: "Korea Republic of" },
    { key: "KW", flag: "kw", value: "Kuwait", text: "Kuwait" },
    { key: "KY", flag: "ky", value: "Cayman Islands", text: "Cayman Islands" },
    { key: "KZ", flag: "kz", value: "Kazakhstan", text: "Kazakhstan" },
    { key: "LA", flag: "la", value: "Lao People's Democratic Republic", text: "Lao People's Democratic Republic" },
    { key: "LB", flag: "lb", value: "Lebanon", text: "Lebanon" },
    { key: "LC", flag: "lc", value: "Saint Lucia", text: "Saint Lucia" },
    { key: "LI", flag: "li", value: "Liechtenstein", text: "Liechtenstein" },
    { key: "LK", flag: "lk", value: "Sri Lanka", text: "Sri Lanka" },
    { key: "LR", flag: "lr", value: "Liberia", text: "Liberia" },
    { key: "LS", flag: "ls", value: "Lesotho", text: "Lesotho" },
    { key: "LT", flag: "lt", value: "Lithuania", text: "Lithuania" },
    { key: "LU", flag: "lu", value: "Luxembourg", text: "Luxembourg" },
    { key: "LV", flag: "lv", value: "Latvia", text: "Latvia" },
    { key: "LY", flag: "ly", value: "Libya", text: "Libya" },
    { key: "MA", flag: "ma", value: "Morocco", text: "Morocco" },
    { key: "MC", flag: "mc", value: "Monaco", text: "Monaco" },
    { key: "MD", flag: "md", value: "Moldova, Republic of", text: "Moldova Republic of" },
    { key: "ME", flag: "me", value: "Montenegro", text: "Montenegro" },
    { key: "MG", flag: "mg", value: "Madagascar", text: "Madagascar" },
    { key: "MH", flag: "mh", value: "Marshall Islands", text: "Marshall Islands" },
    { key: "MK", flag: "mk", value: "Macedonia the former Yugoslav Republic of", text: "Macedonia the former Yugoslav Republic of" },
    { key: "ML", flag: "ml", value: "Mali", text: "Mali" },
    { key: "MM", flag: "mm", value: "Myanmar", text: "Myanmar" },
    { key: "MN", flag: "mn", value: "Mongolia", text: "Mongolia" },
    { key: "MO", flag: "mo", value: "Macao", text: "Macao" },
    { key: "MP", flag: "mp", value: "Northern Mariana Islands", text: "Northern Mariana Islands" },
    { key: "MQ", flag: "mq", value: "Martinique", text: "Martinique" },
    { key: "MR", flag: "mr", value: "Mauritania", text: "Mauritania" },
    { key: "MS", flag: "ms", value: "Montserrat", text: "Montserrat" },
    { key: "MT", flag: "mt", value: "Malta", text: "Malta" },
    { key: "MU", flag: "mu", value: "Mauritius", text: "Mauritius" },
    { key: "MV", flag: "mv", value: "Maldives", text: "Maldives" },
    { key: "MW", flag: "mw", value: "Malawi", text: "Malawi" },
    { key: "MX", flag: "mx", value: "Mexico", text: "Mexico" },
    { key: "MY", flag: "my", value: "Malaysia", text: "Malaysia" },
    { key: "MZ", flag: "mz", value: "Mozambique", text: "Mozambique" },
    { key: "NA", flag: "na", value: "Namibia", text: "Namibia" },
    { key: "NC", flag: "nc", value: "New Caledonia", text: "New Caledonia" },
    { key: "NE", flag: "ne", value: "Niger", text: "Niger" },
    { key: "NF", flag: "nf", value: "Norfolk Island", text: "Norfolk Island" },
    { key: "NG", flag: "ng", value: "Nigeria", text: "Nigeria" },
    { key: "NI", flag: "ni", value: "Nicaragua", text: "Nicaragua" },
    { key: "NL", flag: "nl", value: "Netherlands", text: "Netherlands" },
    { key: "NO", flag: "no", value: "Norway", text: "Norway" },
    { key: "NP", flag: "np", value: "Nepal", text: "Nepal" },
    { key: "NR", flag: "nr", value: "Nauru", text: "Nauru" },
    { key: "NU", flag: "nu", value: "Niue", text: "Niue" },
    { key: "NZ", flag: "nz", value: "New Zealand", text: "New Zealand" },
    { key: "OM", flag: "om", value: "Oman", text: "Oman" },
    { key: "PA", flag: "pa", value: "Panama", text: "Panama" },
    { key: "PE", flag: "pe", value: "Peru", text: "Peru" },
    { key: "PF", flag: "pf", value: "French Polynesia", text: "French Polynesia" },
    { key: "PG", flag: "pg", value: "Papua New Guinea", text: "Papua New Guinea" },
    { key: "PH", flag: "ph", value: "Philippines", text: "Philippines" },
    { key: "PK", flag: "pk", value: "Pakistan", text: "Pakistan" },
    { key: "PL", flag: "pl", value: "Poland", text: "Poland" },
    { key: "PM", flag: "pm", value: "Saint Pierre and Miquelon", text: "Saint Pierre and Miquelon" },
    { key: "PN", flag: "pn", value: "Pitcairn", text: "Pitcairn" },
    { key: "PR", flag: "pr", value: "Puerto Rico", text: "Puerto Rico" },
    { key: "PS", flag: "ps", value: "Palestine", text: "Palestine" },
    { key: "PT", flag: "pt", value: "Portugal", text: "Portugal" },
    { key: "PW", flag: "pw", value: "Palau", text: "Palau" },
    { key: "PY", flag: "py", value: "Paraguay", text: "Paraguay" },
    { key: "QA", flag: "qa", value: "Qatar", text: "Qatar" },
    { key: "RE", flag: "re", value: "Réunion", text: "Réunion" },
    { key: "RO", flag: "ro", value: "Romania", text: "Romania" },
    { key: "RS", flag: "rs", value: "Serbia", text: "Serbia" },
    { key: "RU", flag: "ru", value: "Russian Federation", text: "Russian Federation" },
    { key: "RW", flag: "rw", value: "Rwanda", text: "Rwanda" },
    { key: "SA", flag: "sa", value: "Saudi Arabia", text: "Saudi Arabia" },
    { key: "SB", flag: "sb", value: "Solomon Islands", text: "Solomon Islands" },
    { key: "SC", flag: "sc", value: "Seychelles", text: "Seychelles" },
    { key: "SD", flag: "sd", value: "Sudan", text: "Sudan" },
    { key: "SE", flag: "se", value: "Sweden", text: "Sweden" },
    { key: "SG", flag: "sg", value: "Singapore", text: "Singapore" },
    { key: "SH", flag: "sh", value: "Saint Helena Ascension and Tristan da Cunha", text: "Saint Helena Ascension and Tristan da Cunha" },
    { key: "SI", flag: "si", value: "Slovenia", text: "Slovenia" },
    { key: "SJ", flag: "sj", value: "Svalbard and Jan Mayen Islands", text: "Svalbard and Jan Mayen Islands" },
    { key: "SK", flag: "sk", value: "Slovakia", text: "Slovakia" },
    { key: "SL", flag: "sl", value: "Sierra Leone", text: "Sierra Leone" },
    { key: "SM", flag: "sm", value: "San Marino", text: "San Marino" },
    { key: "SN", flag: "sn", value: "Senegal", text: "Senegal" },
    { key: "SO", flag: "so", value: "Somalia", text: "Somalia" },
    { key: "SR", flag: "sr", value: "Suriname", text: "Suriname" },
    { key: "ST", flag: "st", value: "Sao Tome and Principe", text: "Sao Tome and Principe" },
    { key: "SV", flag: "sv", value: "El Salvador", text: "El Salvador" },
    { key: "SY", flag: "sy", value: "Syrian Arab Republic", text: "Syrian Arab Republic" },
    { key: "SZ", flag: "sz", value: "Swaziland", text: "Swaziland" },
    { key: "TC", flag: "tc", value: "Turks and Caicos Islands", text: "Turks and Caicos Islands" },
    { key: "TD", flag: "td", value: "Chad", text: "Chad" },
    { key: "TF", flag: "tf", value: "French Southern Territories", text: "French Southern Territories" },
    { key: "TG", flag: "tg", value: "Togo", text: "Togo" },
    { key: "TH", flag: "th", value: "Thailand", text: "Thailand" },
    { key: "TJ", flag: "tj", value: "Tajikistan", text: "Tajikistan" },
    { key: "TK", flag: "tk", value: "Tokelau", text: "Tokelau" },
    { key: "TL", flag: "tl", value: "Timor-Leste", text: "Timor-Leste" },
    { key: "TM", flag: "tm", value: "Turkmenistan", text: "Turkmenistan" },
    { key: "TN", flag: "tn", value: "Tunisia", text: "Tunisia" },
    { key: "TO", flag: "to", value: "Tonga", text: "Tonga" },
    { key: "TR", flag: "tr", value: "Turkey", text: "Turkey" },
    { key: "TT", flag: "tt", value: "Trinidad and Tobago", text: "Trinidad and Tobago" },
    { key: "TV", flag: "tv", value: "Tuvalu", text: "Tuvalu" },
    { key: "TW", flag: "tw", value: "Taiwan", text: "Taiwan" },
    { key: "TZ", flag: "tz", value: "Tanzania United Republic of", text: "Tanzania United Republic of" },
    { key: "UA", flag: "ua", value: "Ukraine", text: "Ukraine" },
    { key: "UG", flag: "ug", value: "Uganda", text: "Uganda" },
    { key: "UM", flag: "um", value: "US Minor Outlying Islands", text: "US Minor Outlying Islands" },
    { key: "US", flag: "us", value: "United States", text: "United States" },
    { key: "UY", flag: "uy", value: "Uruguay", text: "Uruguay" },
    { key: "UZ", flag: "uz", value: "Uzbekistan", text: "Uzbekistan" },
    { key: "VA", flag: "va", value: "Holy See (Vatican City State)", text: "Holy See (Vatican City State)" },
    { key: "VC", flag: "vc", value: "Saint Vincent and the Grenadines", text: "Saint Vincent and the Grenadines" },
    { key: "VE", flag: "ve", value: "Venezuela Bolivarian Republic of", text: "Venezuela Bolivarian Republic of" },
    { key: "VG", flag: "vg", value: "Virgin Islands, British", text: "Virgin Islands, British" },
    { key: "VI", flag: "vi", value: "Virgin Islands, U.S.", text: "Virgin Islands, U.S." },
    { key: "VN", flag: "vn", value: "Viet Nam", text: "Viet Nam" },
    { key: "VU", flag: "vu", value: "Vanuatu", text: "Vanuatu" },
    { key: "WF", flag: "wf", value: "Wallis and Futuna Islands", text: "Wallis and Futuna Islands" },
    { key: "WS", flag: "ws", value: "Samoa", text: "Samoa" },
    { key: "YE", flag: "ye", value: "Yemen", text: "Yemen" },
    { key: "YT", flag: "yt", value: "Mayotte", text: "Mayotte" },
    { key: "ZA", flag: "za", value: "South Africa", text: "South Africa" },
    { key: "ZM", flag: "zm", value: "Zambia", text: "Zambia" },
    { key: "ZW", flag: "zw", value: "Zimbabwe", text: "Zimbabwe" }
    ]